# defibrillator
services:
  defibrillator:
      image: docker:cli
      container_name: defibrillator
      hostname: defibrillator
      network_mode: none
      cap_drop:
        - ALL
      volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
      command: [ "/bin/sh", "-c", "while true; do sleep 600; docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart; done" ]
      restart: unless-stopped
